### ISSUE TITLE
Show Gizmos.Draw* on the phone. 

### ISSUE THREAD

**Issue by Cookingsource** [fehaar/FFWD#10]
I'm thinking a lot about  if drawing the gizmos on the device could be interesting, or just testing on the pc in play mode would be enough. 

I sitil think it could be very useful to show the gizmos also in the final device to have an idea of how's everything behaving (Conditionally compiled based on a flag). I've already managed to draw wireframe primitives on a simpler xna wp7 project using the baseEffect. I just need to integrate it with the framework. 

Personally i don't need the solid versions of Gizmos.Draw\* but i could give it some time if you consider them useful too. I need to maximize the time for the dbp2012 entry^^

**Comment by fehaar** [comment]
The reason that I haven't implemented the Gizmos is that in Unity they are only shown on the scene camera, and not in game. As there is no scene cam at the moment in FFWD it didn't make much sense.

You can us the Debug.Draw\* implementations for in-game representation. There are also some additions in FFWD to draw transforms and bounds that will make things easier.

That said. Making a Gizmos class by just using the Debug.Draw\* methods internally should be quite easy to do. You just also have to implement the OnGizmos call to make it work like in Unity.

**Comment by Cookingsource** [comment]
Now that you pointed me to that Debug class,  with it and the DebugCamera I can complete the task. I suppose  you don't want this behavior (draw gizmos on debug deploys) in the main trunk,  so i think this could be closed as invalid issue.

Thanks for you help, and by the way, exploring the code I realized that you don't have coroutines implemented, i would love to implement them for you if you like, ^^

**Comment by fehaar** [comment]
All right. I will close this issue. You are right about coroutines. I haven't had the use for them in our projects. But they should be done, so feel free to implement them. It should not be so hard to do. I actually stumbled upon a blog where someone described how to do iterator based coroutines. I will see if I can find it again.

I will also see if I can assign you to the issue in some way...
