### ISSUE TITLE
Beginner Issue

### ISSUE THREAD

**Issue by jaykannan** [fehaar/FFWD#13]
I don't really understand the usage of this system and I'm new to Unity, and I seem to have missed something obvious.

What does the instruction "Open Unity in the Template directory" mean as Unity only opens unity files? I had to open the one inside Scenes. because of this - I get the error "DirectoryNotFoundException - ..........FFWD-Templates/Unity/Assets\Assets\Scenes under - Main Scenes - when I choose Full Export and it doesnt proceed after that.

I understand the issue, but how do I change the folder to point one level up. Also, where should I put the FFWD folder in relation to the template folder? I tried looking around to set the path and move the files about, but I've had no success.

**Comment by Cookingsource** [comment]
Personally I think it would be better for you to learn the two platforms one by one before mixing them. Once said that.

Open unity means launch Unity, then open project, then select the folder Unity under the template directory. This opens the whole unity project not just the scene.

If you don't change the downloaded template file structure, you have to set the xna content to, ..\XNA
This goes up a folder from your current folder ( Unity ) and selects the XNA folder that should be there. 

The ffwd folder is already created, you just have to unzip the framework in that folder. This is, you should have the folders Demos, Exporter, Framework,... in the FFWD folder of your template. 

Again i don't want to discourage you of doing anything but learning two different platforms at the same time could be a huge task. And you'll have to because sooner or later you will find something you need to implement something not currently supported by the framework ( hopefully contributing here ^^ ) or will need to deal with some issues that require more in depth of unity or xna.

**Comment by fehaar** [comment]
I will take a look at how the Getting Started guide is written and see if I can make things clearer. I am looking into doing a beginners video, but I have no firm timeframe for that.

I hope that the comment from Cookingsource helped you on your way.

**Comment by Laumania** [comment]
+1 for beginner video :)

**Comment by fehaar** [comment]
yeah yeah. I hear you. :)

**Comment by jaykannan** [comment]
I do know XNA / C#, i'm new to Unity and I want to port a friend's Unity3D game into WP7 while learning Unity properly. it kinda meets the criteria that FFWD requires.

**Comment by fehaar** [comment]
Yes it does. Did the post from Cookingsource help you get further? I have changed the documentation to be clearer on what to do. It could sound like you are being bitten by issue #17: https://github.com/fehaar/FFWD/issues/17.

**Comment by jaykannan** [comment]
I'm using the latest source from Git, let me delete everything and start from scratch. will report back

**Comment by fehaar** [comment]
Cool. There have been some updates/fixes since you last wrote.

**Comment by jaykannan** [comment]
This is exactly what I did, after I deleted everything.
1. I GitCloned FFWD-Templates into my work folder
2. I Git-Cloned FFWD into FFWD-Templates\FFWD
3. Opened Unity in the Unity Folder (it didnt let me select anything else)
4. It warned me that rebuilding library since It could not find the asset database
5. I chose full export, no changes to configuration. and it ran beyond the last problem but ended up with this error
        -  Directory "FFWD.Templates.Scripts"not found.

Thnaks for your quick responses.

**Comment by fehaar** [comment]
If you are using the default template it should be "FFWD.Template.Script" - so it seems you have an extra s in there. Can you check your FFWD configuration? When I look at the .config file on Github it seems correct.

**Comment by jaykannan** [comment]
I am using the default template, and I didn't change anything. I got a FFWD.Template.Scripts in the configuration window and the folder inside XNA is also called FFWD.Template.Scripts . I changed it to Script and it didn't work - said --.Script not found.

**Comment by fehaar** [comment]
Can you check the value in the configuration for XNA Base Dir (found at the bottom). To help people collaborate this is not in the configuration file - but saved in the Unity preferences instead. This could be set to the path of your first try. It should be set to a relative default of ..\XNA.

**Comment by fehaar** [comment]
By the way. The extra s was in Templates - not in Scripts. :) The directory is called FFWD.Template.Scripts.

**Comment by jaykannan** [comment]
I've uploaded the images to show you the error

http://imgur.com/a/MfJwL

**Comment by fehaar** [comment]
Change the XNA Base Dir at the bottom of the configuration to ..\XNA and you should be good to go. I have got to have a look at how that is set.

**Comment by jaykannan** [comment]
It worked thanks. I remember reading that before, but I totally forgot about it. My bad.

**Comment by fehaar** [comment]
NP. Just glad you have gotten it solved.

**Comment by jaykannan** [comment]
Still get the Unity scripts folder 'Scripts'not found error, from the middle of the error page. will start slowly working my app into this and see how it goes.

**Comment by fehaar** [comment]
Do you have a folder called Scripts in your Unity project? I can see that it is not there by default in git because it doesn't contain anything. I should really put a test script in there...

**Comment by jaykannan** [comment]
No there's nothing in there.

Also, I got it compiling, but I had to delete the X360 projects for now (as 
they didn't) It's running on the Windows Phone emulator as a blank screen as 
well as on a window.

Could you elaborate on this step 4 in the wiki, maybe edit it to include the 
earlier requirement to add ..\XNA if we're just using the template as well?

---

In the FFWD.Template.XmlContent include the Scene and Assets that have been 

## exported. Do the same in the FFWD.Template.Content project.

Regards
Jay Kannan

-----Original Message-----

**Comment by fehaar** [comment]
I added the ..\XNA to the Wiki earlier, as I could see that it was missing. I will check the 360 project. Maybe it is just missing some references. It is fair enough that the screen is blank - because the default scene in the template does not show anything at the moment.

**Comment by jaykannan** [comment]
Thanks for the help. I'm kinda getting the hang of it. could you put in some 
coding standards or practices that'll force a predictable pipeline for 
development. that way, we can ensure that the exports are always 100% 
compatible.

-----Original Message-----

**Comment by fehaar** [comment]
I will work on that as I get reports on what people are missing. It is kind of what we are doing with the project that we are currently making with FFWD. There are a lot of different ways of using Unity, so it is pretty hard to know all the small parts we are missing.
