### ISSUE TITLE
Could you say more about the starting

### ISSUE THREAD

**Issue by akira32** [fehaar/FFWD#16]
1.Open Unity in the template directory.
2.Choose the menu item FFWD and select the Full export option

What is the template directory?
I saw the two FFWD in unity. But no "Full export option" in unity. Only export package. Thanks!

**Comment by fehaar** [comment]
The "template directory" is the directory that you have checked the FFWD-Templates project out to. More specifically it is the subdirectory called Unity in that folder. You should make Unity open the project there.

When you do that you will have a FFWD menu in the top menu bar of Unity where the Full Export menu item is listed.

I can see that I need to change the wording here. :)

**Comment by fehaar** [comment]
I have changed the first item on the list to be more specific.
