### ISSUE TITLE
FFWD Full Export error

### ISSUE THREAD

**Issue by akira32** [fehaar/FFWD#17]
DirectoryNotFoundException: Directory 'C:/tmp/fehaar-FFWD-Templates-435bb02/fehaar-FFWD-Templates-435bb02/Unity/Assets\Assets\Scenes' not found.
I open the default unity project and Full Export, it appear the error message as above.

**Comment by fehaar** [comment]
Open the menu item Configuration in the FFWD menu. Open the drop down arrows for Config | Groups | Main scenes. Change the "Base Scene Dir" to Scenes instead of Assets\Scenes and it will work.

You can also just update Templates from Git as I have fixed the default configuration now.
