### ISSUE TITLE
Support for XBox controllers

### ISSUE THREAD

**Issue by fehaar** [fehaar/FFWD#19]
The Input class is quite weak because it has mostly been used for touch based things. Make it work for the XBox as well.

**Comment by Elideb** [comment]
Partial solution (GetAxis) in pull request #24. Will implement GetButtons when I decide how to do it. Name buttons "A", "B"... as the Xbox does, or use the default Unity button names ("Fire1", "Jump"...)?

**Comment by fehaar** [comment]
You can find the Unity spec in this document: http://dl.dropbox.com/u/691629/UnityController.zip

**Comment by Elideb** [comment]
In my fork I've added support for GetButton in PC and Xbox (and GetButton("Back") in WP7). In the end I've included "Fire1"/"A", "Fire2"/B", "Fire3"/"X", "Jump"/"Y", "Start"/"Pause", "Back", "Up", "Left", "Down", "Right", "LB"/"LeftButton", "RB"/RightButton", "LT"/LeftTrigger" and "RT"/"RightTrigger". Only the first four are understood if no pad is available.

I also added "LeftTrigger", "RightTrigger" and "TriggerCombined" to GetAxis, if a pad is connected.

If those changes are pulled in, this can be closed. Unfortunately, I've had a misunderstanding with Git's branches and in the end all the code resides in my master branch. I'll try to maintain everything in its own branch from now on, so features can be pulled individually.

**Comment by fehaar** [comment]
Very cool. Do you have a pull request?

**Comment by Elideb** [comment]
Yep, this was inside pull request #30, with all the rest. I've tested the Xbox controller on PC and things seem to work fine.

**Comment by fehaar** [comment]
Fantastic. I will close it then.
