### ISSUE TITLE
Implement a default version of GetAxis 

### ISSUE THREAD

**Issue by fehaar** [fehaar/FFWD#22]
The GetAxis calls on input should at least work for the default Unity setting (ie. not customized by the player)

**Comment by Elideb** [comment]
I'm doing this currently in my project. Currently I intend to map "Horizontal" and "Vertical" to WASD on PC and main analogue on Xbox (taking [GameDefaults.MoveWithRightThumbStick](http://msdn.microsoft.com/en-us/library/microsoft.xna.framework.gamerservices.gamedefaults.movewithrightthumbstick.aspx) on account), and "Horizontal2" and "Vertical2" to arrows on PC and secondary analogue on Xbox.
If that's good enough for you, I'll let you know when that's finished.

In the long term I want to implement as much of Input as I need for PC and Xbox. That'll include Xbox buttons and triggers, with equivalent axis.

**Comment by fehaar** [comment]
Excellent. That was exactly what I was thinking of doing as a default version.

**Comment by Elideb** [comment]
I'd say this can be closed already, since #24 took care of it.
