### ISSUE TITLE
Audio Issues

### ISSUE THREAD

**Issue by Cookingsource** [fehaar/FFWD#23]
Hi, i've been trying to play some audio with the engine but i don't find the correct way. I create an empty gameobject, then I add to it an audiosource, then a script that plays an audio depending on some input. The input is correctly detected. 

The audiosource is not added as component to the said gameobject in its serialized xml.

I tried to workaround this issue adding the audiosource component at runtime, but the audio didn't play either. After that i realized that the sound var from the audioclip is null, and of course its Instance property.

The audios are two wavs. I've explored the audio related classes but i don't find the source of sound being null. Nor the thing about the audiosource not being added to the components of the gameobject.

**Comment by fehaar** [comment]
Do you have a project I can look at? Otherwise I will try to cook up a demo with sounds working.

**Comment by Cookingsource** [comment]
I'll make a small demo of the issue so i can send it to you. 

Btw, i have a couple of questions. 
what's the workflow for using audio? 
Is the listener required(for xna FFWD)? It seems it is played directly from the audioclip. 
Should the audiosources get serialized automatically if i set one in a scene GO? 
Do I have to make some special treatment to the wavs or mp3s so the clips are initialized properly? (mine have their sound var null at runtime, so the Instance is also null)

Thanks for your quick reply, this is vital to my dbp entry since is a very musical game.

**Comment by fehaar** [comment]
The listener is not required - and not even exported. It only really makes sense for 3D audio - that I have not made an attempt at doing yet.

BTW - as I recall, the audio files might not be copied over by the export process. The AudioSources should be in the scene XMLs and have a reference to the file as usual. They should also try to load up the file (and play automatically if that is checked). So you will get an error in the output log if the file is not there.

You will want to use WAV files in XNA as there AFAIK still is a memory leak with MP3's on the Phone - unless you play them with the XNA MediaPlayer. So for SFX using the AudioSource, you should use WAVs.

**Comment by Cookingsource** [comment]
http://www.2shared.com/file/wgHBkpDY/AudioIssue.html
I attach a sample project with the issue, i observed these things for now:

The audios are not being copied to the content with the full export.
The audiosource component is not being serialized, it plays normally in unity but after exporting it doesn't show in the logo scene xml, so it isnt' reflected once loaded on the device.

I can't go any further without your help. With that solved i could test a little bit more the other things about the audioclips not being correctly loaded.

**Comment by fehaar** [comment]
I found out that the info to support exporting AudioSources had gone from the configuration. In the project we are working on now, the gameplay guys had decided to export Audio in an other way and do things by script. This is the configuration I had added to FFWD. You could actually see when Unity exported that it logged a message saying it skipped the AudioSource.

I also cleaned up the code a bit, as there were some properties on the AudioSource that is no longer supported in 3.5.

The template and FFWD have been updated. I have a fixed version of your project here:
http://dl.dropbox.com/u/691629/AudioIssue.zip

**Comment by fehaar** [comment]
I also added sound to the Test scene, "SkinnedAnimation" so it is possible to see it in action there.
