### ISSUE TITLE
Camera exports unused fields

### ISSUE THREAD

**Issue by Elideb** [fehaar/FFWD#25]
Note: this issue is probably related to Unity 3.5.

Everytime I export a scene, three elements appear on the XML definition:

```
      <hdr>false</hdr>
      <!-- ortographicSize, ortographic, etc. -->
      <useOcclusionCulling>true</useOcclusionCulling>
      <layerCullSpherical>false</layerCullSpherical>
```

None of them are used by the camera and cause the importer to throw a couple of errors, first because ortographicSize is not found where it should be, later because the last two fields are not understood. For the build to finish I have to comment the three of them.

I've checked the Unity exporter configuration and seen that none of these fields are excluded. Should they be? I doubt, because currently I'm using Unity 3.5 and this fields might be new (hdr is for sure). Will the export fail in previous versions of Unity if a non-existant field is excluded?

Related links:
[Camera in Unity](http://unity3d.com/support/documentation/ScriptReference/Camera.html)
[FFWD exporter configuration](https://github.com/fehaar/FFWD/blob/master/Exporter/PressPlay.FFWD.Exporter/App.config)

**Comment by fehaar** [comment]
I have actually updated the Exporter config file in the Templates project last week to export the correct camera settings. And it is, as you guessed, due to Unity 3.5. So if you use the new exporter confic, the values should export correctly. The new config also has support for AudioSources that had gone missing.

**Comment by fehaar** [comment]
Regarding this: "Will the export fail in previous versions of Unity if a non-existant field is excluded?". No. The exporter will just check the fields that it finds versus the fields in the config file. So you will not get errors if non-existant fields are named.
