### ISSUE TITLE
Combine Animation xmls

### ISSUE THREAD

**Issue by fehaar** [fehaar/FFWD#4]
The animation XMLs are split into seperate animations. Combine them into less files to help load times.

**Comment by stanleyjoy** [comment]
I have a Character that uses 41 animations. The FBX.xml is around 150kb and the animation.xml is around 7mb is there a workaround bout the size of the FBX model animation or is it something that I cant fix.

**Comment by fehaar** [comment]
Wow. That is an extremely large animation output. Can you tell me what the size of the .xnb file is after XNA has compiled it? It is possible to use another more condensed format for the animations than XML. But you will have to write the importer components for doing that yourself. The way to go about it would be to have a ContentProcessor that can read the XML file and then write a reader and writer for some compact format that you define yourself. It should not be that hard to do, as the content pipeline in XNA is highly extensible.

**Comment by stanleyjoy** [comment]
I am kind of an ace in Unity 3D and just started with XNA. I made 3 games in XNA but all of them in 2D (so safe to say I am noob in 3D XNA). My boss wants me to push a 3D game that we have on iOS and Android to WP7 and since its 3D, I went for FFWD.
Since its Mayday or Labor day here in India, my office is on holiday and we will start working from tomorrow. Then I will be able to check it out the size of the XNB and get back to you.
You also mentioned that XNA WP7 uses around 6 shaders any other shader will be spat out. Any ideas what shader I must use in Unity 3D to work in XNA.
By the way awesome work on this plugin. I am really stunned that you guys got Unity to work for XNA. Hope Unity and Microsoft don't cause any problems in legality issues. 
-Stan
P.S. Max and the Magic Marker is awesome, but loved tentacles even better.

**Comment by stanleyjoy** [comment]
The .xnb for the FBX is around 100KB and the animation.XML.xnb is around 2.8MB.

**Comment by fehaar** [comment]
It is still pretty large, but there is also a lot of animations in there. But if you don't have many characters with that many animations it should not be a problem. If it gets to be an issue with space I suggest that you go for creating your own binary format that can probably get smaller than the FBX.

There is no legality problems. The Unity guys know what we are doing, and obviously Microsoft does as well - as they have published the games.

I am glad that you like our games!

**Comment by stanleyjoy** [comment]
Ok thanks.

What bout the shaders???
Stan

**Comment by fehaar** [comment]
Ah. Sorry. Missed it. XNA only has a limited set of built in shaders and no support for doing custom shaders for WP7. Generally FFWD will use the standard BasicEffect shader for everything no matter what shader you set in Unity. It will use the other shaders for specific purposes like lightmaps and skinned animation. So normally you don't have to worry about it because you don't really have a lot of available options. The only thing you can worry about is that things don't look exactly like in Unity. In that regard you might have to be creative...

**Comment by stanleyjoy** [comment]
Ok then!!
so i will have to take a leap of faith. We will have to go with the 2.8 MB XNB no other go. 
Working on the UI right now.
Stan
Thanks for all the help

**Comment by stanleyjoy** [comment]
Does FFWD support GUIStyle???
Stan

**Comment by fehaar** [comment]
It has very limited preliminary support for it - aka. the classes are there in some form and some of the settings are working. But you will most probably need to fill out some blanks (and maybe give me a pull request ;-)

**Comment by stanleyjoy** [comment]
I was trying to do a button clicked and I am not able to do so with the GUIStyle also. I found that a GUI.Button with the overloads Rectangle, string and GUIStyle is not recognized by FFWD.
When I tried to just add empty texture and carry on I started having problems with Scene.xml which is trying to run the GUIStyle script.
Stan

**Comment by fehaar** [comment]
Can you file a new issue on this and describe the issue or provide enough info so I can reproduce the problem. Then I can look at what is going on.
