### ISSUE TITLE
PhysicMaterial

### ISSUE THREAD

**Issue by mydiscogr** [fehaar/FFWD#42]
Hi, I'm using physics and 2d works well but I've tried to add physic material to a cube and setting Bounciness .50 in xna version nothing happen, it's my fault or isn't implemented or any workaround ?
thanks

**Comment by fehaar** [comment]
Nope. Physics materials are not exported from Unity, so you will have to change the collider exporter scripts to export the data, and then add a class to import it into XNA. It should be possible to apply the properties to the bodies in the Physics engine when the properties get to XNA.

**Comment by mydiscogr** [comment]
ok thanks :)
