### ISSUE TITLE
tombstone... for wp7

### ISSUE THREAD

**Issue by mydiscogr** [fehaar/FFWD#44]
Hi, I'm new about ffwd and I wonder if there's a way to implement tombstone or helper...
any Idea?

Thanks

**Comment by fehaar** [comment]
You would implement this directly in XNA. In your Game1.cs for instance. FFWD does not interfere here.

**Comment by mydiscogr** [comment]
ok thanks :)

**Comment by mydiscogr** [comment]
ok thanks :)

**Comment by mydiscogr** [comment]
ok thanks :)
