### ISSUE TITLE
Is the FFWD will be keep updating?

### ISSUE THREAD

**Issue by dekaralos** [fehaar/FFWD#60]
Hi Thomas,

I'm one of developer that working on proting unity to Windows Phone 8. Is there any planning to keep this framework keep updates?

regards,
Dekaralos

**Comment by fehaar** [comment]
At the moment FFWD is not actively being updated, as you can probably see in the commit logs. Unity have announced native Windows Phone 8 support, rendering FFWD obsolete for that platform anyway, and there is no word from Microsoft whether XNA will still be a proper platform on WP8. So just use Unity and you will be fine.
