### ISSUE TITLE
Farseer Physics....

### ISSUE THREAD

**Issue by stanleyjoy** [fehaar/FFWD#66]
I have a doubt on which Farseer Physics to use. There is one Farseer Physics on the Unity Asset store and one in Codeplex. Which one do we need to use to make it work on FFWD???
Stan

**Comment by fehaar** [comment]
There is a Farseer engine bundled with FFWD. If you need to update it, update it from Codeplex. The one in the Unity Asset store is tuned to work in Unity and will probably not work with FFWD.

**Comment by stanleyjoy** [comment]
So i should use the polygon collider to use Farseer Physics..
Stan

**Comment by fehaar** [comment]
In XNA you will always use Farseer for all your basic colliders exported from Unity.

If you specifically need Farseer polygon colliders in XNA you can make them with the provided helper script. Just be aware that they will not work in the Unity editor or player. Only in XNA.
