### ISSUE TITLE
Raycast support

### ISSUE THREAD

**Issue by stanleyjoy** [fehaar/FFWD#68]
Does FFWD support Raycast??
I want to get Raycast for hit. thats why,
Stan

**Comment by fehaar** [comment]
Yes it does. Just be very aware of the plane you are casting rays in as the physics aer in 2D. That has proven to be difficult to grasp for some users. If you are having issues with it, look at the coordinates that are actualy getting passed into the bowels of Farseer and see that they are the proper coordinates.
