### ISSUE TITLE
Last but not least.

### ISSUE THREAD

**Issue by stanleyjoy** [fehaar/FFWD#72]
I am about to upload my game to Windows Phone Marketplace when I got this issue.

I changed the build setting from debug to release. 
I did change the Assembly information in the properties of my Active Project (WP7). The Info I changed was the Title and the Product name.
When i build the game I get this error
Error loading pipeline assembly "D:\Project\XNA\XNA\FFWD.Template.Scripts\bin\x86\Release\FFWD.Templates.Scripts.dll".            PROJECT: FFWD.Template.Win
Error loading pipeline assembly "D:\Project\XNA\XNA\FFWD.Template.Scripts\bin\x86\Release\FFWD.Templates.Scripts.dll".            PROJECT: FFWD.Template.Win
Error loading pipeline assembly "D:\Project\XNA\XNA\FFWD.Template.Scripts\bin\x86\Release\FFWD.Templates.Scripts.dll".            PROJECT: FFWD.Template.WP7
Error loading pipeline assembly "D:\Project\XNA\XNA\FFWD.Template.Scripts\bin\x86\Release\FFWD.Templates.Scripts.dll".            PROJECT: FFWD.Template.WP7

Any ideas why??
Stan

**Comment by stanleyjoy** [comment]
When I build in Debug Mode it works.

**Comment by fehaar** [comment]
Check the Build Configuration in Visual Studio to see if any of the projects have been disabled for build in Release mode.

**Comment by stanleyjoy** [comment]
I have built all the solutions (Mixed Platforms) then it worked. Since I kept Configuration to only build for WP7 it did not build for x86 or Xbox 360. When I gave this it rebuilt everything. 
Thanks Thomas for everything our game is ready and is undergoing Closed Beta Testing here in India.
Stan

**Comment by fehaar** [comment]
Excellent Stan! I am looking forward to seeing it when it is out there. Good luck!
