### ISSUE TITLE
I Solved issue that some might get.

### ISSUE THREAD

**Issue by stanleyjoy** [fehaar/FFWD#73]
Got a funky bug...

When I was jumping between scenes, the game crashes. [Menu -> Game -> Menu -> (Crash)]

It is pointing a Null Reference error to Compare Tag method in the Component.cs 

Check Code

<code>
Component.cs
 #region Public methods
        public bool CompareTag(string tag)
        {
              return gameObject.CompareTag(tag);                 // NULL ISSUE FIRES HERE
        }
   #endregion
</code>

While debugging the return boolean of that method is a null at the point of crash.

The solution.
I think the Component.cs is called or compiled before the GameObject.cs which causes the null reference issue. All we need to do is to check if gameObject is not null

<code>
Component.cs
 #region Public methods
        public bool CompareTag(string tag)
        {
            if (gameObject != null)                                      // If condition to check if gameObject is not null
            {
                return gameObject.CompareTag(tag);
            }
            return false;
        }
        #endregion
</code>

Using the if condition solves this issue. All though still no idea whether we would have any side effects.

Stan

If any please Post em.

**Comment by fehaar** [comment]
It sounds like you are tyring to call CompareTag on a component that has been destroyed. Are you doing it on a cached component reference? Checking for null is a valid method of preventing a crash though.

**Comment by stanleyjoy** [comment]
I was not using the compare tag at all. you can try it if you want.
if it means anything the Tag that it always tries to compare is the Main Camera.
Stan
