### ISSUE TITLE
Finally uploaded and LIVE.

### ISSUE THREAD

**Issue by stanleyjoy** [fehaar/FFWD#78]
Hey Thomas,
Good news we finally uploaded our game and it passed the screening process. 
Our game is live finally.
http://www.windowsphone.com/en-in/store/app/mini-carrom/a7c2a8e8-ee21-492f-8e3b-f1814ebd1cbc

We have uploaded our next game and its waiting for review. Thank you for constant support.

Stanley J. Maliackal
Gameplay Programmer
Nextwave Multimedia

**Comment by fehaar** [comment]
Congratilations Stanley. Way to go!
