### ISSUE TITLE
Any movement here? Bepu Physics?

### ISSUE THREAD

**Issue by bigdaddio** [fehaar/FFWD#79]
Has this project been abandoned? Ignored? Lost? Any movement on the 3D physics?

**Comment by fehaar** [comment]
Time has run from this project. Microsoft has more or les abandoned XNA moving forward and Unity is supporting Windows Phone 8. Furthermore the projects we had internally using it was laid down, so the "official" line of development is gone as well. So unfortunately there is not much movement here.
