### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by schuranator** [fehaar/FFWD#80]
I was wondering if there is a specific way to add asset store plugins into the code. Should I move the plugin to the scripts folder? I'm trying to bring over 2D toolkit. If you can give me a general idea how this would be done or if I need to recode the plugin or if you have an example of how you were able to add sprites to your game that would be great.

I have been playing around with this Framework for two week and have found my way around things to make the porting work so far but I'm looking to start on the 2D background and 2D toolkit is not moving in so nice.

**Comment by fehaar** [comment]
You will need to have the source code for the plugin and port that along with your other source as you would normally do. DLL's wont work.
