### ISSUE TITLE
FFWD works with Windows Phone 8

### ISSUE THREAD

**Issue by stephan7** [fehaar/FFWD#82]
I'm using FFWD to create a 3D game for Windows Phone 8. Instead of XNA I use MonoGame.

First gameplay video here:
http://www.mombari.com/

For use with Windows Phone 8 / MonoGame a few adaptations and extensions were necessary. Since FFWD has a very good architecture and high code quality, it was easy and fun to develop these extensions. In fact, I was able to do that without asking a single question about FFWD.

BTW: I'm aware that Unity is supporting Windows Phone 8 soon ;-) 

I will write about some technical details of the process a blog post soon.

Just wanted to say thank you for your great work, Thomas!

Stephan

**Comment by fehaar** [comment]
Wow Stephan! Great work and thanks for the kind words about quality. I am looking forward to your blog post and great to see FFWD being taken in new directions.
